### ISSUE TITLE
Registration bugs

### ISSUE THREAD

**Issue by danielleung27** [Helen300/BboyGen#1]
1) Prevent registration of same username/email. Currently it allows same username registration and it overwrites existing account.

2) Prevent user from making too short of a password (reject the request and give them a warning message)

**Comment by Helen300** [comment]
https://stackoverflow.com/questions/36910373/django-rest-auth-allauth-registration-with-email-first-and-last-name-and-witho


 this might help us

**Comment by Helen300** [comment]
https://iheanyi.com/journal/user-registration-authentication-with-django-django-rest-framework-react-and-redux/

**Comment by Helen300** [comment]
https://dev.to/callmetarush/the-django-rest-custom-user-model-and-authentication-5go9

**Comment by Helen300** [comment]
https://stackoverflow.com/questions/40575634/user-creation-with-unique-constraint-in-django-rest-framework

**Comment by Helen300** [comment]
https://github.com/pennersr/django-allauth/blob/ff44f32187b996d7920475a7204c2291fd692e77/allauth/account/adapter.py#L238

**Comment by Helen300** [comment]
fixed #2 in #73
