### ISSUE TITLE
when move/set not selected, show help messages

### ISSUE THREAD

**Issue by danielleung27** [Helen300/BboyGen#114]
like princetoncourses, use extra space to show help messages

**Comment by Helen300** [comment]
List view
1. Click on move to edit/reverse/change move type/ add details 
2. Drag and drop moves to reorder them 
3. Select move type and input name to add move 

Generator view
1. Click on a set to view current moves/add/delete moves 
2. Click on move to add it to the current set 
3. Use edit probabilities to change transition probabilities/ etc.. for adding random moves 
4. drag and drop moves / sets to reorder them 

Training
1. Use edit probabilities to change 
2. Use durations to change how long..
3. Select a training set to train moves from that set, unselect to train all moves 
4. Press play to start training,

**Comment by danielleung27** [comment]
done with pr #123
