### ISSUE TITLE
Show move type in MoveDetail

### ISSUE THREAD

**Issue by danielleung27** [Helen300/BboyGen#23]
Show move type in MoveDetail so we can know what type a move is without going through the tabs

**Comment by Helen300** [comment]
can you clarify what this means? like you dont want the tabs or you want to keep tabsbut also specify move?

**Comment by Helen300** [comment]
gotcha

**Comment by Helen300** [comment]
shouldwe show its typein the other tabs

**Comment by Helen300** [comment]
showed it, just need to do some styling

**Comment by danielleung27** [comment]
> shouldwe show its typein the other tabs

Nah, looks good right now! I think we can style later, closing issue now.
