### ISSUE TITLE
Unselect move when clicking outside

### ISSUE THREAD

**Issue by danielleung27** [Helen300/BboyGen#24]
Unselect move when clicking anywhere outside MoveList

**Comment by Helen300** [comment]
https://stackoverflow.com/questions/32553158/detect-click-outside-react-component

**Comment by Helen300** [comment]
https://medium.com/@pitipatdop/little-neat-trick-to-capture-click-outside-react-component-5604830beb7f

**Comment by danielleung27** [comment]
Decided to only unselect the move when clicking on the move again.
