### ISSUE TITLE
Selection jumps when dragging

### ISSUE THREAD

**Issue by danielleung27** [Helen300/BboyGen#38]
Selection jumps from original position to new position really fast when dragging. Ends up with the correct thing but this UI glitch is a little unappealing. Maybe use react-beautiful-dnd package to do selection styling instead of using our own?
https://egghead.io/lessons/react-customise-the-appearance-of-an-app-during-a-drag-using-react-beautiful-dnd-snapshot-values

**Comment by Helen300** [comment]
hmm i dont particularly understand this? what do you mean it jumps from original position? i feel like mine looks pretty normal and nice

**Comment by danielleung27** [comment]
Fixed in pr #109
