### ISSUE TITLE
Tabbed moves list view

### ISSUE THREAD

**Issue by danielleung27** [Helen300/BboyGen#4]
Finish #2 first

Separate tabs to show only top rock, only footwork, etc

**Comment by Helen300** [comment]
created separate tabs, but filtering not completed
made for all, toprock, footwork, power 
should we be doing a separate list for each, or filter through to get all that are of specific key value, but not sure if javascript has a helpful method for filtering

**Comment by Helen300** [comment]
if we go with move_list --> footwork, power, balalal, list then need to update state in movelistview

**Comment by Helen300** [comment]
i think this is done
