### ISSUE TITLE
When logging in, it takes you back to landing page

### ISSUE THREAD

**Issue by danielleung27** [Helen300/BboyGen#62]
When logging in, it takes you back to landing page for a second or 2 before taking you to the MoveListView. Ideally it should stall on the login page until it logs in, and then go to MoveListView.

**Comment by Helen300** [comment]
made it so that it shows a loadiing, but not sure if this is how we want it.

**Comment by Helen300** [comment]
#72

**Comment by danielleung27** [comment]
Completed
