### ISSUE TITLE
Make draggable

### ISSUE THREAD

**Issue by danielleung27** [Helen300/BboyGen#9]
Make list of moves draggable
Use package 'react-beautiful-dnd'

Things to keep in mind
1) Autoscroll when mousedown around bottom or top of move list
2) Don't trigger on click events when dragging things around
3) Possibly add UI elements to indicate that the cards can be dragged?

**Comment by Helen300** [comment]
https://motion.ant.design/exhibition/demo/list-sort

**Comment by danielleung27** [comment]
Completed with pr #34
